### ISSUE TITLE
SPC file format reader

### ISSUE THREAD

**Issue by ssuwelack** [paucablop/chemotools#70]
Are there any plans to include an SPC file format reader? Or can you recommend a different Python OSS library that can be used with chemotools?

**Comment by paucablop** [comment]
Hello @ssuwelack 

Thank you for your suggestion. Initially, my plan was to develop an IO module featuring lightweight readers for common formats. However, I haven't prioritized it just yet, as there are already some excellent open-source alternatives available. In the past, I found success using the library at this link: https://github.com/NickMacro/spc-spectra/tree/master, which can be installed using ```pip install spc_spectra```

This library works well with a diverse range of SPC files. You can utilize it to read SPC files, extracting absorbance/intensity and wavenumbers/wavelengths arrays as ```numpy.ndarray```. These arrays can be used directly with ```chemotools```. 😊

Feel free to give it a try! If you find functionalities that could use improvement or if there's something missing, I am open to considering implementations in ```chemotools```. Your feedback is always welcome and valued! 🚀

**Comment by ssuwelack** [comment]
Cool, thanks for the hint! I'll give it a try!
