### ISSUE TITLE
ModuleNotFoundError when loading  from chemotools.variable_selection import RangeCut

### ISSUE THREAD

**Issue by jguenther504** [paucablop/chemotools#78]
I wanted to try your Coffee Spectra Classifier exercise in google colab but when I run the line

from chemotools.variable_selection import RangeCut

I receive the following error. 

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-22-1f1aa1b9255b>](https://localhost:8080/#) in <cell line: 7>()
      5 from chemotools.scatter import StandardNormalVariate
      6 
----> 7 from chemotools.variable_selection import RangeCut
      8 pipeline = make_pipeline(
      9     StandardNormalVariate(),

ModuleNotFoundError: No module named 'chemotools.variable_selection'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

Can you please help?
Thank you

**Comment by paucablop** [comment]
Hi @jguenther504 thanks for reaching out and highlighting the issue. It is because in order to align with the scikit-learn naming convention, I changed the name module name from variable_selection to feature_selection, and I forgot to update the coffee exercise! 

If you type 

from feature_selection import RangeCut

it should work! :) I will update the exercise as soon as possible! Thanks for pointing it out!

With best regards

Pau

**Comment by paucablop** [comment]
@jguenther504, I have updated the documentation on the exercises and also of the methods. 

- Here you can find the [updated coffee exercise](https://paucablop.github.io/chemotools/get-started/coffee_spectra_classifier.html)

- Here you can find the [updated documentation of feature selectors](https://paucablop.github.io/chemotools/docs/feature_selection.html)

I hope this resolves the issues, else please let me know :) 

With best regards, 

Pau

**Comment by paucablop** [comment]
This issue is closed after updating the documentation and verifying module works as described
